name: Build and publish image

on: [ push ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sign In
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: |
          docker build -t php-nginx .
      - name: Publish images
        run: |
          docker tag php-nginx parsilver/php:8.0-nginx
          docker push parsilver/php:8.0-nginx

